version: '2'
services:

  pgpool2:
    image: eeacms/pgpool
    restart: always
    depends_on: 
      - pg-0
    environment:
      - PGPOOL_MASTER=0:pg-0:5432
      - PGPOOL_BACKENDS=1:pg-1:5432
        #,2:pg-2:5432
      - PCP_USER=pcpuser
      - PCP_USER_PASSWORD=pcppassword
    ports:
      - 5432:5432/tcp

  pg-0:
    image: docker.io/bitnami/postgresql-repmgr:11
    #4.2.0
    #privileged: true
    restart: always
    #volumes:
    #  - postgres_data-0:/bitnami/postgresql/data
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=pgpassword
      - POSTGRESQL_USERNAME=pcpuser
      - POSTGRESQL_PASSWORD=pcppassword
      - POSTGRESQL_DATABASE=databasename
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=pg-0,pg-1:5432
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
      - REPMGR_PORT_NUMBER=5432
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes

  pg-1:
    image: docker.io/bitnami/postgresql-repmgr:11
    restart: always
    #volumes:
    #  - postgres_data-1:/bitnami/postgresql/data
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=pgpassword
      - POSTGRESQL_USERNAME=keycloak65rA
      - POSTGRESQL_PASSWORD=pcppassword
      - POSTGRESQL_DATABASE=databasename
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=pg-0,pg-1:5432
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
      - REPMGR_PORT_NUMBER=5432
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
